# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.books]
file = "libre-book/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["books"] }

[print_schema.users]
file = "libre-user/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["users"] }

[migrations_directory]
dir = "/home/samuka/workspace/libre/ModernLibre/service/migrations"
