openapi: 3.0.0
info:
  title: Libre Service Api V1
  version: '1.0'
paths:
  /books/details/{bookId}:
    get:
      summary: Get Metadata
      description: Get metadata of book with given ID.
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookMeta'
    post:
      summary: (Deprecated) Create a New Book
      description: Create a new book with the provided metadata.
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookMeta'
      responses:
        '201':
          description: Book created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookMeta'
    put:
      summary: Update Book Metadata
      description: Update metadata of the book with the given ID.
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookMeta'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookMeta'
    delete:
      summary: Delete Book
      description: Delete the book with the given ID.
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
  /books/list:
    get:
      summary: List Books
      description: If `by` is not specified, then random books are responsed.
      parameters:
        - name: by
          in: query
          schema:
            type: string
            enum:
              - id
              - top-rated
              - recent
            default: id
        - name: pagenum
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookMeta'
  /books/download:
    get:
      summary: Download Book
      description: Download the book with the given ID and extension.
      parameters:
        - name: bookId
          in: query
          required: true
          schema:
            type: integer
        - name: extension
          in: query
          required: true
          schema:
            type: string
            enum:
              - pdf
              - epub
              - mobi
              - txt
      security:
        - bearerAuth: []
      responses:
        '302':
          description: Redirect to download link
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: https://example.com/books/123/download.pdf
        '404':
          description: Book not found
  /books/upload:
    post:
      summary: Upload a Book
      description: Upload a new book file.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Book uploaded successfully
        '400':
          description: Invalid file format
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    BookMeta:
      type: object
      properties:
        id:
          type: integer
          example: 123
        title:
          type: string
          example: Professional C++
        author:
          type: string
          example: Marc Gregoire
        description:
          type: string
          example: Expand your C++ knowledge quickly and efficiently with this advanced resource
        status:
          type: integer
          example: 0
        rating:
          type: number
          format: float
          example: 4.5
        added_date:
          type: integer
          example: 1735939200
          description: 添加时间
        categories:
          type: array
          items:
            type: string
          example:
            - cs
            - tutorial
            - c++
          description: 书本分类
        cover_url:
          type: string
          example: https://m.media-amazon.com/images/I/81qqfxAlzwL._SL1500_.jpg
          description: 封面图片URL
